### ISSUE TITLE
Setup RBAC authorisation with Google Group Role provider

### ISSUE THREAD

**Issue by jaksky** [GoogleCloudPlatform/spinnaker-for-gcp#207]
Hello,

I am trying to setup Spinnaker which is accessed via IAP (external protected access - instead of kubectl tunnel) together with RBAC authorisation describe in this [RBAC authorisation manual](https://spinnaker.io/setup/security/authorization/).

I see users logged in in the UI which is OK with the ability to logout. However, when I enable authz with Gooogle G-suite role provider according this [manual](https://spinnaker.io/setup/security/authorization/google-groups/) I am getting error on all my pipelienes
```
userXXX@company is not authorized (account: YYY, description: KubernetesDeployManifestDescription
```
Though I see that my kubernetes provider has permissions configured as follows:
```
    kubernetes:
      enabled: true
      accounts:
      - name: YYY
        requiredGroupMembership: []
        providerVersion: V2
        permissions:
          READ:
          - engineering
          WRITE:
          - engineering
        dockerRegistries: []
```
and user  userXXX@gmail.com  is a member of engineering@company group in google groups. 

When I enable [authn with OAuth](https://spinnaker.io/setup/security/authentication/oauth/google) I cannot access my spinnaker instance as I am redirected to some login page which doesn't work and seems to me that it is clashing with IAP so I guess that IAP is in place of authn and cannot coexist both. 

I don't see any roles available in pipelines permissions config
![image](https://user-images.githubusercontent.com/5112307/96280682-8e51a500-0fd8-11eb-8c49-557a96af933b.png)

 which seems to me more as an issue with Role provider configuration though I wasn't able to find anything in the logs and don't see fiat component actually running in deployment. 

Could someone more experienced provide some hint?

**Comment by jaksky** [comment]
My deployment for some reason doesn't have fiat component deployed.

![image](https://user-images.githubusercontent.com/5112307/97812357-198d9480-1c81-11eb-9f65-2f717cb2b67f.png)

I am starting with spinnaker so just followed the tutorial where the version is fixed to: 1.19.3
According to spinnaker release notes: https://spinnaker.io/community/releases/versions/1-19-3-changelog#spinnaker-release-1-19-0
Which should contain a version of fiat 1.10

I would appreciate some hints from more experienced users

**Comment by jaksky** [comment]
What is confusing is that configuration file contains:
```
  features:
    auth: false
    fiat: false
```

But I see authz enabled:
```
    authz:
      groupMembership:
        service: GOOGLE
        google:
          roleProviderType: GOOGLE
          credentialPath: /home/spinnaker/.hal/default/credentials/spinnaker-fiat.json
          adminUsername: infra-admins@xxx.yy
          domain: xxx.yy
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
        ldap:
          roleProviderType: LDAP
      enabled: true
```
