### ISSUE TITLE
Handle fiat "File" role provider

### ISSUE THREAD

**Issue by Tangeek59** [GoogleCloudPlatform/spinnaker-for-gcp#77]
Currently testing spinnaker for GCP, I'm facing an issue with the fiat "File" role provider.

This provider need a path to a file describing each roles, I can update the role provider config.
But when I try to push it the path is not rewritten with the halyard user.

Current config in `.hal/config` :
```
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
          path: /home/my_user/.hal/default/credentials/fiat-file.yaml
        ldap:
          roleProviderType: LDAP
      enabled: true
```

Error durring `push_and_apply.sh`

```
Problems in Global:
! ERROR Failed to backup user file:
  /home/my_user/.hal/default/credentials/fiat-file.yaml
- Failed to deploy Spinnaker.
```

I'm currently using a workaround with manual editing of `.hal/config` to :
```
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
          path: /home/spinnaker/.hal/default/credentials/fiat-file.yaml
        ldap:
          roleProviderType: LDAP
      enabled: true
```
